# sensor-service application.properties
spring.application.name=sensor-service

# alle Endpunkte offen zugänglich
management.endpoints.web.exposure.include=*

# Configserver ---------------------------------------------------------------------------------------------------------
spring.config.import=optional:configserver:http://localhost:8888/