# sensor-service application.properties
spring.application.name=sensor-service

# alle Endpunkte offen zugänglich
management.endpoints.web.exposure.include=*

# Configserver ---------------------------------------------------------------------------------------------------------
spring.config.import=optional:configserver:http://localhost:8888/

# Datenbank-Verbindung -------------------------------------------------------------------------------------------------
spring.datasource.url=jdbc:mysql://localhost:3306/sensors_db
spring.datasource.username=root
spring.datasource.password=PasswordGroup7
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true