spring.application.name=gateway-service
server.port=8081

#Endpoints zugänglich
management.endpoints.web.exposure.include=*

# Configserver ---------------------------------------------------------------------------------------------------------
spring.config.import=optional:configserver:http://localhost:8888/